substitutions:
  _REGION: us-central1
  _REPOSITORY: containers
  _IMAGE: forge
  _TAG: review-required

steps:
  - id: build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --pull
      - --tag
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${_TAG}
      - .

  - id: push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${_TAG}

images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${_TAG}

options:
  logging: CLOUD_LOGGING_ONLY

